version: '2'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    command: lein run
    depends_on:
      - database
      - api
  repl:
    build: .
    command: lein repl
    volumes:
      - .:/code
    working_dir: /code
  database:
    build: ./database
    volumes:
      - . :/var/lib/postgresql
    ports:
      - "5432:5432"
  api:
    image: begriffs/postgrest:latest
    ports:
      - "3000:3000"
    command: [ postgrest, "postgres://postgres@database:5432/postgres",
              -a, "guest", 
              -p, "3000",
              -s, "v1",
              -j, "jwt-secret",
              -o, "10",
              -m, "25000" ]
    depends_on:
      - database
