version: '2'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/dbdata
    depends_on:
      - database
      - api
  database:
    build: ./database
    ports:
      - "5432:5432"
  api:
    image: begriffs/postgrest:latest
    ports:
      - "3000:3000"
    command: postgrest postgres://database:5432/postgres -a anonymous -p 3000 -s v1 -j jwt-secret -o 10 -m 250000
    depends_on:
      - database
