version: '2'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/dbdata
    depends_on:
      - database
      - api
  database:
    build: ./database
    ports:
      - "5432:5432"
  api:
    image: begriffs/postgrest:latest
    ports:
      - "3000:3000"

